import test from 'node:test';
import assert from 'node:assert/strict';
import {Player,World,box,ramp,CFG} from '../physics.mjs';
import {createMap} from '../map.mjs';
const floor=()=>box([-10000,-10000,-100],[10000,10000,0]);
const make=(extra=[])=>new Player(new World([floor(),...extra]));
const run=(p,n,input={},yaw=0)=>{for(let i=0;i<n;i++)p.tick(input,yaw);};
test('unarmed run reaches 260 units/s',()=>{const p=make();run(p,128,{forward:true});assert.ok(Math.abs(p.speed-260)<.001);});
test('diagonal input cannot exceed forward running speed',()=>{const p=make();run(p,128,{forward:true,right:true});assert.ok(Math.abs(p.speed-260)<.001);});
test('first ground tick uses acceleration 5.5',()=>{const p=make();p.tick({forward:true});assert.ok(Math.abs(p.speed-5.5*260/64)<.001);});
test('walk is 52% and crouch is 34% of unarmed speed',()=>{const p=make();run(p,200,{forward:true,walk:true});assert.ok(Math.abs(p.speed-135.2)<.01);p.reset();run(p,200,{forward:true,duck:true});assert.ok(Math.abs(p.speed-88.4)<.01);assert.equal(p.height,54);});
test('counter-strafe stops earlier than releasing movement',()=>{const a=make(),b=make();run(a,64,{forward:true});run(b,64,{forward:true});let coast=0,counter=0;while(a.vel[0]>.1&&coast<100){a.tick();coast++;}while(b.vel[0]>.1&&counter<100){b.tick({back:true});counter++;}assert.ok(counter<coast);});
test('gravity integration gives approximately 57-unit jump',()=>{const p=make();let peak=0;for(let i=0;i<70;i++){p.tick({jump:i===0});peak=Math.max(peak,p.pos[2]);}assert.ok(peak>56&&peak<58,`peak ${peak}`);assert.ok(p.grounded);});
test('holding jump does not auto-bhop',()=>{const p=make();run(p,200,{jump:true});assert.equal(p.jumps,1);assert.ok(p.grounded);});
test('air acceleration caps wish projection at 30',()=>{const p=make();p.reset([0,0,500]);run(p,3,{forward:true});assert.ok(Math.abs(p.vel[0]-30)<.001);});
test('air strafe can add sideways speed without ground friction',()=>{const p=make();p.reset([0,0,500]);p.vel=[250,0,0];p.tick({right:true});assert.equal(p.vel[0],250);assert.equal(p.vel[1],-30);assert.ok(p.speed>250);});
test('jump caps bunnyhop speed to 1.1x maxspeed',()=>{const p=make();p.vel=[400,0,0];p.tick({jump:true});assert.ok(Math.abs(p.speed-286)<.001);});
test('landing applies stamina and recovery restores it',()=>{const p=make();p.tick({jump:true});assert.ok(p.stamina>20);while(!p.grounded)p.tick();assert.ok(p.stamina>10);run(p,100);assert.equal(p.stamina,0);});
test('swept hull cannot tunnel through thin wall',()=>{const p=make([box([100,-1000,0],[101,1000,300])]);p.reset([0,0,80]);p.vel=[3500,0,0];run(p,10);assert.ok(p.pos[0]<84.01);});
test('wall contact preserves tangential movement',()=>{const p=make([box([100,-1000,0],[110,1000,300])]);p.reset([80,0,.03125]);run(p,60,{forward:true,left:true});assert.ok(p.pos[0]<=84.001);assert.ok(p.pos[1]>100);});
test('16-unit steps are traversable',()=>{const p=make([box([50,-100,0],[100,100,16]),box([100,-100,0],[160,100,32])]);p.reset([0,0,.03125]);run(p,30,{forward:true});assert.ok(p.pos[0]>80);assert.ok(p.pos[2]>15);});
test('24-unit step blocks walking',()=>{const p=make([box([50,-100,0],[200,100,24])]);p.reset([0,0,.03125]);run(p,60,{forward:true});assert.ok(p.pos[0]<34.01);});
test('ramp can be ascended while staying grounded',()=>{const p=make([ramp([50,-100,0],[450,100,100])]);p.reset([0,0,.03125]);run(p,64,{forward:true});assert.ok(p.pos[2]>35);assert.ok(p.grounded);});
test('ceiling prevents standing from crouch',()=>{const p=make([box([50,-100,60],[300,100,100])]);p.reset([0,0,.03125]);run(p,120,{forward:true,duck:true});assert.ok(p.pos[0]>50);run(p,64);assert.equal(p.height,54);assert.equal(p.duck,1);});
test('air crouch shifts origin by 9 and can be reversed',()=>{const p=make();p.reset([0,0,400]);p.tick({duck:true});assert.equal(p.height,54);assert.ok(p.pos[2]>408);run(p,30,{duck:true});p.tick();assert.equal(p.height,72);});
test('map spawn is grounded and unobstructed',()=>{const p=new Player(createMap());assert.ok(p.grounded);assert.ok(!p.trace(p.pos,p.pos).solid);});
test('render rate grouping does not change fixed-tick simulation',()=>{const a=make(),b=make();run(a,128,{forward:true});for(let frame=0;frame<32;frame++)run(b,4,{forward:true});assert.deepEqual(a.pos,b.pos);assert.deepEqual(a.vel,b.vel);});
test('descending ramp maintains ground contact',()=>{const p=make([ramp([0,-100,0],[512,100,128],true)]);p.reset([40,0,128]);run(p,15);assert.ok(p.grounded);run(p,60,{forward:true});assert.ok(p.grounded);assert.ok(p.pos[0]>200);assert.ok(p.pos[2]<90);});
test('jump into a ceiling stops vertical ascent',()=>{const p=make([box([-100,-100,100],[100,100,140])]);p.reset([0,0,.03125]);let peak=0;for(let i=0;i<60;i++){p.tick({jump:i===0});peak=Math.max(peak,p.pos[2]);}assert.ok(peak<=28);assert.ok(p.grounded);});
